#!/bin/bash

if [ -z "${ANDROIDPATH}" ]; then
    if [ `hostname` == "alux" ]; then
	export ANDROID_ROOT='/usr/share/android'
	export LINKOFFLINE="-linkoffline $ANDROID_ROOT/docs/reference $ANDROID_ROOT/docs/reference"
	export WORLDWIND_DOCS='-linkoffline /usr/share/doc/worldwind-doc /usr/share/doc/worldwind-doc'
    else
	export ANDROID_ROOT='/home/benjamin/bin/android-sdk-linux_86'
	export LINKOFFLINE="-linkoffline http://developer.android.com/reference/ $ANDROID_ROOT/docs/reference"
    fi
fi

export ANDROIDPATH="$ANDROID_ROOT/platforms/android-8/android.jar"
export CLASSPATH=$ANDROIDPATH:$CLASSPATH:./lib/simplegraph/:`ls -1 jars/*.jar jars/worldwind/*.jar | xargs | sed "s/ /:/g"`:.

if [ 'heartless' == "$1" ]; then
    export HEARTLESS='--heartless'
fi

OSNAME=`uname`

if [ 'Linux' == "$OSNAME" ]; then
    DOCK=
else
    DOCK='-Xdock:icon=img/logo.png -Xdock:name=HorizonServer'
fi

clean() {
    echo "Clean old classfiles" 1>&2
    rm -f org/haldean/chopper/server/*.class
    echo "Clean backup java files" 1>&2
    rm -f org/haldean/chopper/server/*.java\~
}

run() {
    java -Djava.library.path=/lib/:jars/worldwind/:jars/ -Xmx512m \
	-Dsun.java2d.noddraw=true $DOCK org.haldean.chopper.server.ServerCreator \
	-h droidcopter.cs.columbia.edu:7000 -d $HEARTLESS
}

doc() {
    javadoc -author -version -d doc/ $LINKOFFLINE $WORLDWIND_DOCS \
	-classpath $CLASSPATH -sourcepath . -windowtitle "Robocopter Documentation" \
	`ls -d org/haldean/chopper/*/ | sed "s/[\/]*$//" | sed "s/\//./g" | xargs`
}

check() {
    checkstyle -c style-checks.xml -r org/ -o doc/check-results.txt
}

build() {
    javac org/haldean/chopper/server/ServerCreator.java -Xlint:deprecation
}

if [ 'clean' == "$1" ]; then
    clean
    exit
fi

if [ 'pack' == "$1" ]; then
    echo "Creating archive" 1>&2
    tar -czf server.tar.gz org unit
elif [ 'doc' == "$1" ]; then
    doc
elif [ 'open-doc' == "$1" ]; then
    gnome-open doc/index.html &> /dev/null
elif [ 'check' == "$1" ]; then
    clean
    check
elif [ 'nobuild' == "$1" ]; then
    run
elif [ 'build' == "$1" ]; then
    clean
    build
else
    clean
    build && echo "Compiled" 1>&2 && run
fi
