all:	fred fred_extended brock_a brock_b benedict

benedict:
	openscad -s stl/benedict.stl scad/benedict.scad

fred:
	openscad -s stl/fred.stl scad/fred.scad

fred_extended:
	openscad -s stl/fred_extended.stl scad/fred_extended.scad

brock_a:
	openscad -s stl/brock_a.stl scad/brock_a.scad

brock_b:
	openscad -s stl/brock_b.stl scad/brock_b.scad